# Copyright 2019-present Facebook Inc. All rights reserved.
# This source code is licensed under the Apache 2.0 license found
# in the LICENSE file in the root directory of this source tree.

# Fetch base gremlin server image
FROM tinkerpop/gremlin-server:3.4.11

# Copy overriden server configuration.
COPY gremlin-server.yaml tinkergraph-empty.properties /opt/gremlin-server/conf/
