// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

package codegen

import "github.com/facebook/ent/schema"

// Annotation is a builtin schema annotation for attaching
// metadata to schema objects for both codegen and runtime.
type Annotation struct {
	// The PackageName option allows overriding the default package
	// name that is generated by ent. For example:
	//
	//	codegen.Annotation{
	//		PackageName: "dbuser",
	//	}
	//
	PackageName string `json:"package_name,omitempty"`
}

// Name describes the annotation name.
func (Annotation) Name() string {
	return "Type"
}

// Merge implements the schema.Merger interface.
func (a Annotation) Merge(other schema.Annotation) schema.Annotation {
	var ant Annotation
	switch other := other.(type) {
	case Annotation:
		ant = other
	case *Annotation:
		if other != nil {
			ant = *other
		}
	default:
		return a
	}
	if t := ant.PackageName; t != "" {
		a.PackageName = t
	}
	return a
}

var (
	_ schema.Annotation = (*Annotation)(nil)
	_ schema.Merger     = (*Annotation)(nil)
)
